/**
 * Permission Code Constants
 * Used for RBAC throughout the frontend
 */

export enum PermissionCode {
  // Dashboard
  ORG_DASHBOARD_VIEW = 'ORG_DASHBOARD_VIEW',

  // Organization & Staff
  ORG_STAFF_READ = 'ORG_STAFF_READ',
  ORG_STAFF_CREATE = 'ORG_STAFF_CREATE',
  ORG_STAFF_UPDATE = 'ORG_STAFF_UPDATE',
  ORG_STAFF_DELETE = 'ORG_STAFF_DELETE',

  // Departments
  ORG_DEPARTMENT_READ = 'ORG_DEPARTMENT_READ',
  ORG_DEPARTMENT_CREATE = 'ORG_DEPARTMENT_CREATE',
  ORG_DEPARTMENT_UPDATE = 'ORG_DEPARTMENT_UPDATE',
  ORG_DEPARTMENT_DELETE = 'ORG_DEPARTMENT_DELETE',

  // Designations
  ORG_DESIGNATION_READ = 'ORG_DESIGNATION_READ',
  ORG_DESIGNATION_CREATE = 'ORG_DESIGNATION_CREATE',
  ORG_DESIGNATION_UPDATE = 'ORG_DESIGNATION_UPDATE',
  ORG_DESIGNATION_DELETE = 'ORG_DESIGNATION_DELETE',

  // Locations
  ORG_LOCATION_READ = 'ORG_LOCATION_READ',
  ORG_LOCATION_CREATE = 'ORG_LOCATION_CREATE',
  ORG_LOCATION_UPDATE = 'ORG_LOCATION_UPDATE',
  ORG_LOCATION_DELETE = 'ORG_LOCATION_DELETE',

  // Attendance
  ORG_ATTENDANCE_READ = 'ORG_ATTENDANCE_READ',
  ORG_ATTENDANCE_CREATE = 'ORG_ATTENDANCE_CREATE',
  ORG_ATTENDANCE_UPDATE = 'ORG_ATTENDANCE_UPDATE',
  ORG_ATTENDANCE_DELETE = 'ORG_ATTENDANCE_DELETE',

  // Leave
  ORG_LEAVE_REQUEST_READ = 'ORG_LEAVE_REQUEST_READ',
  ORG_LEAVE_REQUEST_CREATE = 'ORG_LEAVE_REQUEST_CREATE',
  ORG_LEAVE_REQUEST_APPROVE = 'ORG_LEAVE_REQUEST_APPROVE',
  ORG_LEAVE_REQUEST_REJECT = 'ORG_LEAVE_REQUEST_REJECT',

  ORG_LEAVE_TYPE_READ = 'ORG_LEAVE_TYPE_READ',
  ORG_LEAVE_TYPE_MANAGE = 'ORG_LEAVE_TYPE_MANAGE',

  ORG_HOLIDAY_READ = 'ORG_HOLIDAY_READ',
  ORG_HOLIDAY_MANAGE = 'ORG_HOLIDAY_MANAGE',

  // Projects
  ORG_PROJECT_READ = 'ORG_PROJECT_READ',
  ORG_PROJECT_CREATE = 'ORG_PROJECT_CREATE',
  ORG_PROJECT_UPDATE = 'ORG_PROJECT_UPDATE',
  ORG_PROJECT_DELETE = 'ORG_PROJECT_DELETE',

  // Tasks
  ORG_TASK_READ = 'ORG_TASK_READ',
  ORG_TASK_CREATE = 'ORG_TASK_CREATE',
  ORG_TASK_UPDATE = 'ORG_TASK_UPDATE',
  ORG_TASK_DELETE = 'ORG_TASK_DELETE',

  // Milestones
  ORG_MILESTONE_READ = 'ORG_MILESTONE_READ',
  ORG_MILESTONE_MANAGE = 'ORG_MILESTONE_MANAGE',

  // Payroll
  ORG_PAYROLL_READ = 'ORG_PAYROLL_READ',
  ORG_PAYROLL_CREATE = 'ORG_PAYROLL_CREATE',
  ORG_PAYROLL_UPDATE = 'ORG_PAYROLL_UPDATE',
  ORG_PAYROLL_PROCESS = 'ORG_PAYROLL_PROCESS',

  // Salary Structure
  ORG_SALARY_STRUCTURE_READ = 'ORG_SALARY_STRUCTURE_READ',
  ORG_SALARY_STRUCTURE_MANAGE = 'ORG_SALARY_STRUCTURE_MANAGE',

  // Invoices
  ORG_INVOICE_READ = 'ORG_INVOICE_READ',
  ORG_INVOICE_CREATE = 'ORG_INVOICE_CREATE',
  ORG_INVOICE_APPROVE = 'ORG_INVOICE_APPROVE',

  // Expenses
  ORG_EXPENSE_READ = 'ORG_EXPENSE_READ',
  ORG_EXPENSE_CREATE = 'ORG_EXPENSE_CREATE',
  ORG_EXPENSE_APPROVE = 'ORG_EXPENSE_APPROVE',

  // Accounts
  ORG_ACCOUNT_READ = 'ORG_ACCOUNT_READ',
  ORG_ACCOUNT_MANAGE = 'ORG_ACCOUNT_MANAGE',

  // Courses
  ORG_COURSE_READ = 'ORG_COURSE_READ',
  ORG_COURSE_CREATE = 'ORG_COURSE_CREATE',
  ORG_COURSE_UPDATE = 'ORG_COURSE_UPDATE',
  ORG_COURSE_DELETE = 'ORG_COURSE_DELETE',

  // Enrollments
  ORG_ENROLLMENT_READ = 'ORG_ENROLLMENT_READ',
  ORG_ENROLLMENT_CREATE = 'ORG_ENROLLMENT_CREATE',
  ORG_ENROLLMENT_UPDATE = 'ORG_ENROLLMENT_UPDATE',

  // Exams
  ORG_EXAM_READ = 'ORG_EXAM_READ',
  ORG_EXAM_CREATE = 'ORG_EXAM_CREATE',
  ORG_EXAM_GRADE = 'ORG_EXAM_GRADE',

  // Contacts
  ORG_CONTACT_READ = 'ORG_CONTACT_READ',
  ORG_CONTACT_CREATE = 'ORG_CONTACT_CREATE',
  ORG_CONTACT_UPDATE = 'ORG_CONTACT_UPDATE',
  ORG_CONTACT_DELETE = 'ORG_CONTACT_DELETE',

  // Opportunities
  ORG_OPPORTUNITY_READ = 'ORG_OPPORTUNITY_READ',
  ORG_OPPORTUNITY_CREATE = 'ORG_OPPORTUNITY_CREATE',
  ORG_OPPORTUNITY_UPDATE = 'ORG_OPPORTUNITY_UPDATE',

  // Job Postings
  ORG_JOB_POSTING_READ = 'ORG_JOB_POSTING_READ',
  ORG_JOB_POSTING_CREATE = 'ORG_JOB_POSTING_CREATE',
  ORG_JOB_POSTING_UPDATE = 'ORG_JOB_POSTING_UPDATE',

  // Inventory
  ORG_INVENTORY_READ = 'ORG_INVENTORY_READ',
  ORG_INVENTORY_CREATE = 'ORG_INVENTORY_CREATE',
  ORG_INVENTORY_UPDATE = 'ORG_INVENTORY_UPDATE',

  // Warehouses
  ORG_WAREHOUSE_READ = 'ORG_WAREHOUSE_READ',
  ORG_WAREHOUSE_MANAGE = 'ORG_WAREHOUSE_MANAGE',

  // Assets
  ORG_ASSET_READ = 'ORG_ASSET_READ',
  ORG_ASSET_CREATE = 'ORG_ASSET_CREATE',
  ORG_ASSET_UPDATE = 'ORG_ASSET_UPDATE',

  // Messages & Notifications
  ORG_MESSAGE_READ = 'ORG_MESSAGE_READ',
  ORG_MESSAGE_CREATE = 'ORG_MESSAGE_CREATE',
  ORG_MESSAGE_DELETE = 'ORG_MESSAGE_DELETE',

  ORG_NOTIFICATION_READ = 'ORG_NOTIFICATION_READ',

  // Calendar
  ORG_CALENDAR_READ = 'ORG_CALENDAR_READ',
  ORG_CALENDAR_MANAGE = 'ORG_CALENDAR_MANAGE',

  // Reports
  ORG_REPORT_READ = 'ORG_REPORT_READ',
  ORG_REPORT_EXPORT = 'ORG_REPORT_EXPORT',

  // Admin
  ADMIN_USER_READ = 'ADMIN_USER_READ',
  ADMIN_USER_CREATE = 'ADMIN_USER_CREATE',
  ADMIN_USER_UPDATE = 'ADMIN_USER_UPDATE',
  ADMIN_USER_DELETE = 'ADMIN_USER_DELETE',

  ADMIN_ROLE_MANAGE = 'ADMIN_ROLE_MANAGE',
  ADMIN_PERMISSION_MANAGE = 'ADMIN_PERMISSION_MANAGE',

  ADMIN_SYSTEM_SETTINGS = 'ADMIN_SYSTEM_SETTINGS',
  ADMIN_AUDIT_LOG_READ = 'ADMIN_AUDIT_LOG_READ',
}

export default PermissionCode;
